version: "3.8"

services:
  bedrock-server:
    build: .
    container_name: bedrock-server
    ports:
      - "${PORT}:19132/udp"
    volumes:
      - ./server_data:/bedrock
    stdin_open: true
    tty: true
